# Generated by Django 5.1.7 on 2025-05-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invertedindex',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_entries', to='document_search.document'),
        ),
        migrations.AlterField(
            model_name='invertedindex',
            name='term',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='invertedindex',
            unique_together={('term', 'document')},
        ),
        migrations.AddIndex(
            model_name='invertedindex',
            index=models.Index(fields=['term'], name='document_se_term_edab0b_idx'),
        ),
    ]
